---
# tasks file for docker-install
- name: "Check Docker Installation"
  shell: systemctl status docker | grep running
  register: docker_status
  changed_when: False
  #failed_when: docker_version.stdout == '' or docker_version.stdout == 'stopped'

- name: "Install Docker"
  yum:
    name: "{{ docker_package }}"
    state: latest
  become: yes
  when: docker_status is not defined

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  notify: docker facts
